resilience4j.retry:
  instances:
    hello-retry:
      maxAttempts: 3
      waitDuration: 1s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - java.io.IOException
    #  ignoreExceptions:
     #   - com.jsession4d.samplerest.BusinessException